### ISSUE TITLE
Too many escape characters / backslashes

### ISSUE THREAD

**Issue by MartinMajewski** [Xyfi/typescript-react-snippets#3]
This is a great extension, but sadly I get too many backslash characters and have to delete them every time manually.

See picture of a freshly inserted snippet:

![bildschirmfoto 2016-12-15 um 10 55 43](https://cloud.githubusercontent.com/assets/2221289/21219535/7dcbc9be-c2b5-11e6-945d-73734e8ec003.png)

**Comment by ollwenjones** [comment]
same here.

**Comment by StevenTCramer** [comment]
Pull Request submitted

**Comment by abotteram** [comment]
I am sorry for the late reaction guys. The PR has been merged and published.
